Marketing site update
prosopo/prosopo-website pull request #56
Opened 2023-09-26 20:44 UTC by forgetso

2023-09-27 10:55 UTC, forgetso reviewed
Just need some clarification on extra attributes.

2023-09-27 10:55 UTC, forgetso commented on src/_includes/navbar.njk
> +    <div x-data="{ open: false }" class="relative flex flex-col w-full p-5 mx-auto bg-white md:items-center md:justify-between md:flex-row md:px-6 lg:px-8">
Are these tags meant to make the navbar work with css?
```
x-data="{ open: false }"
```
```
@click="open = !open"
```

2023-09-28 15:50 UTC, goastler requested changes

2023-09-28 15:50 UTC, goastler commented on src/assets/scripts/formValidation.js
> +    const inputs = Array.from(form.getElementsByTagName('INPUT'))
why all caps?

2023-09-28 15:58 UTC, forgetso commented on src/assets/scripts/formValidation.js
> +    const inputs = Array.from(form.getElementsByTagName('INPUT'))
Was just debugging. If you look at the names returned by JS, it actually stores them in caps.

```
document.body.nodeName
'BODY'
```

2023-09-28 18:10 UTC, goastler commented on src/assets/scripts/formValidation.js
> +    const inputs = Array.from(form.getElementsByTagName('INPUT'))
oh, fair enough :)

2023-09-28 18:12 UTC, goastler approved these changes

2023-09-28 18:16 UTC, merged